yml 스크립트 수정2

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -36,9 +36,15 @@ jobs:
 
       # 테스트를 수행합니다.
       - name: Run tests
-        run: yarn test
+        run: yarn test:report
 
-      # 앞의 작업이 실패/성공과 관계 없이 컨테이너들을 종료합니다.
-      - name: Stop containers
-        if: always()
-        run: docker-compose -f "docker-compose.yml" down
+      # 테스트 결과를 담은 xml 파일을 레포트로 변환합니다.
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure() # run this step even if previous step failed
+        with:
+          name: test-results
+          path: junit.xml
+          fail-on-error: "false"
+          reporter: jest-junit # Format of test results
+          token: ${{ secrets.GITHUB_TOKEN }}
